title: Zhuotao Wang
description: Web & Security Engineer

# Build settings
markdown: kramdown
exclude: [vendor/ruby]

# Personalization
email: zhuotao26@outlook.com
keybase_username: abhn
twitter_username: abhn_
reddit_username: abhn

# absolute or relative
profile_picture: assets/images/IMG_0129.jpg

# Google Analytics ID
google_analytics: 
